# db/seeds.rb

require 'faker'
Faker::Config.locale = 'pt-BR'

puts "Iniciando seed..."

# 1. Create Institutions from real data
puts "Criando instituições reais..."

institution_names = [
  "Faculdade de Tecnologia de São Paulo",
  "Faculdade de Tecnologia de Sorocaba \"José Crespo Gonzales\"",
  "Faculdade de Tecnologia de Americana \"Ministro Ralph Biasi\"",
  "Faculdade de Tecnologia da Baixada Santista Rubens Lara",
  "Escola Técnica Estadual Polivalente de Americana",
  "Escola Técnica Estadual Conselheiro Antonio Prado",
  "Escola Técnica Estadual Vasco Antonio Venchiarutti",
  "Escola Técnica Estadual João Batista de Lima Figueiredo",
  "Escola Técnica Estadual Lauro Gomes",
  "Escola Técnica Estadual Jorge Street",
  "Escola Técnica Estadual Prof. Camargo Aranha",
  "Escola Técnica Estadual Getúlio Vargas",
  "Escola Técnica Estadual Júlio de Mesquita",
  "Escola Técnica Estadual Presidente Vargas",
  "Escola Técnica Estadual Fernando Prestes",
  "Escola Técnica Estadual Rubens de Faria e Souza",
  "Escola Técnica Estadual São Paulo",
  "Escola Técnica Estadual Dr. Adail Nunes da Silva",
  "Faculdade de Tecnologia de Jahu",
  "Faculdade de Tecnologia de Ourinhos",
  "Faculdade de Tecnologia de Taquaritinga - Profa. Marlene Maria Miletta Servidoni",
  "Escola Técnica Estadual Albert Einstein",
  "Escola Técnica Estadual Prefeito Alberto Feres",
  "Escola Técnica Estadual Prof. Alcídio de Souza Prado",
  "Escola Técnica Estadual Prof. Alfredo de Barros Santos",
  "Escola Técnica Estadual Amin Jundi",
  "Escola Técnica Estadual Sebastiana Augusta de Moraes",
  "Escola Técnica Estadual Professora Anna de Oliveira Ferraz",
  "Escola Técnica Estadual Antonio de Pádua Cardoso",
  "Escola Técnica Estadual Antônio Devisate",
  "Escola Técnica Estadual Prof. Dr. Antonio Eufrásio Toledo",
  "Escola Técnica Estadual Antonio Junqueira da Veiga",
  "Escola Técnica Estadual Prof. Aprígio Gonzaga",
  "Escola Técnica Estadual Aristóteles Ferreira",
  "Escola Técnica Estadual Prof. Armando Bayeux da Silva",
  "Escola Técnica Estadual Frei Arnaldo Maria de Itaporanga",
  "Escola Técnica Estadual Astor de Matos Carvalho",
  "Escola Técnica Estadual Augusto Tortolero  Araújo",
  "Escola Técnica Estadual Comendador João Rays",
  "Escola Técnica Estadual Prof. Basílides de Godoy",
  "Escola Técnica Estadual Benedito Storani",
  "Escola Técnica Estadual Bento Quirino",
  "Escola Técnica Estadual Prof. Marcos Uchoas dos Santos Penchel",
  "Escola Técnica Estadual Carlos de Campos",
  "Escola Técnica Estadual Prof. Carmelino Correia Junior",
  "Escola Técnica Estadual Dr. Carolino da Mota e Silva",
  "Escola Técnica Estadual Cônego José Bento",
  "Escola Técnica Estadual Dr. Dário Pacheco Pedroso",
  "Escola Técnica Estadual Doutor Demétrio Azevedo Júnior",
  "Escola Técnica Estadual Dr. Domingos Minicucci Filho",
  "Escola Técnica Estadual Prof.a Carmelina Barbosa",
  "Escola Técnica Estadual Professor Edson Galvão",
  "Escola Técnica Estadual Elias Nechar",
  "Escola Técnica Estadual Eudécio Luiz Vicente",
  "Escola Técnica Estadual Cel. Fernando Febeliano da Costa",
  "Escola Técnica Estadual Prof. Francisco dos Santos",
  "Escola Técnica Estadual Deputado Francisco Franco",
  "Escola Técnica Estadual Dr. Francisco Nogueira de Lima",
  "Escola Técnica Estadual Francisco Garcia",
  "Escola Técnica Estadual Guaracy Silveira",
  "Escola Técnica Estadual Prof.a Helcy M. Martins Aguiar",
  "Escola Técnica Estadual Engenheiro Herval Bellusci",
  "Escola Técnica Estadual Professor Horácio Augusto da Silveira",
  "Escola Técnica Estadual de Ilha Solteira",
  "Escola Técnica Estadual Jacinto Ferreira de Sá",
  "Escola Técnica Estadual João Belarmino",
  "Escola Técnica Estadual João Gomes de Araújo",
  "Escola Técnica Estadual João Jorge Geraissate",
  "Escola Técnica Estadual Joaquim Ferreira do Amaral",
  "Escola Técnica Estadual Dr. José Coury",
  "Escola Técnica Estadual Prefeito José Esteves",
  "Escola Técnica Estadual Dr. José Luiz Viana Coutinho",
  "Escola Técnica Estadual José Martiniano da Silva",
  "Escola Técnica Estadual Padre José Nunes Dias",
  "Escola Técnica Estadual José Rocha Mendes",
  "Escola Técnica Estadual Prof. José Santana de Castro",
  "Escola Técnica Estadual Dr. Júlio Cardoso",
  "Escola Técnica Estadual Laurindo Alves de Queiroz",
  "Escola Técnica Estadual Dr. Luiz Cesar Couto",
  "Escola Técnica Estadual Prof. Luiz Pires Barbosa",
  "Escola Técnica Estadual Machado de Assis",
  "Escola Técnica Estadual Manoel dos Reis Araújo",
  "Escola Técnica Estadual Orlando Quagliato",
  "Escola Técnica Estadual Martin Luther King",
  "Escola Técnica Estadual Martinho di Ciero",
  "Escola Técnica Estadual Prof. Matheus Leite Abreu",
  "Escola Técnica Estadual Monsenhor Antônio Magliano",
  "Escola Técnica Estadual Eng. Agr. Narciso de Medeiros",
  "Escola Técnica Estadual Prof. Urias Ferreira",
  "Escola Técnica Estadual Paulino Botelho",
  "Escola Técnica Estadual Paulo Guerreiro Franco",
  "Escola Técnica Estadual Deputado Paulo Ornellas C. de Barros",
  "Escola Técnica Estadual Pedro Badran",
  "Escola Técnica Estadual Pedro D arcádia Neto",
  "Escola Técnica Estadual Pedro Ferreira Alves",
  "Escola Técnica Estadual Pedro Leme Brisolla Sobrinho",
  "Escola Técnica Estadual Philadelpho Gouveia Netto",
  "Escola Técnica Estadual Prof. Milton Gazetti",
  "Escola Técnica Estadual Rosa Perrone Scavone",
  "Escola Técnica Estadual Sales Gomes",
  "Escola Técnica Estadual Dona Sebastiana De Barros",
  "Escola Técnica Estadual Prof. Dr. Sylvio De Mattos Carvalho",
  "Escola Técnica Estadual Trajano Camargo",
  "Faculdade de Tecnologia de Indaiatuba \"Dr. Archimedes Lammoglia\"",
  "Faculdade de Tecnologia de Guaratinguetá - Prof. João Mod",
  "Escola Técnica Estadual Adolpho Berezin",
  "Escola Técnica Estadual Coronel Raphael Brandão",
  "Faculdade de Tecnologia de Franca \"Dr. Thomaz Novelino\"",
  "Escola Técnica Estadual Deputado Salim Sedeh",
  "Faculdade de Tecnologia da Zona Leste",
  "Faculdade de Tecnologia de Botucatu",
  "Faculdade de Tecnologia de Mauá",
  "Faculdade de Tecnologia de Jundiaí \"Deputado Ary Fossen\"",
  "Escola Técnica Estadual de Hortolândia",
  "Escola Técnica Estadual de São Roque",
  "Escola Técnica Estadual Prof. Dr. José Dagnoni",
  "Escola Técnica Estadual de Guaianazes",
  "Faculdade de Tecnologia de Garça - \"Deputado Julio Julinho Marcondes de Moura\"",
  "Faculdade de Tecnologia de Mococa \"Mario Robertson de Sylos Filho\"",
  "Faculdade de Tecnologia de São José do Rio Preto",
  "Escola Técnica Estadual Dona Escolástica Rosa",
  "Escola Técnica Estadual Doutor Renato Cordeiro",
  "Escola Técnica Estadual Dr. Celso Charuri",
  "Escola Técnica Estadual Dr. Geraldo Jose Rodrigues Alckimin",
  "Faculdade de Tecnologia de São Bernardo do Campo \"Adib Moises Dib\"",
  "Fatec Cruzeiro - Prof. Waldomiro May",
  "Escola Técnica Estadual de Mauá",
  "Faculdade de Tecnologia de Praia Grande",
  "Faculdade de Tecnologia de Marília",
  "Faculdade de Tecnologia de Itapetininga - Prof Antonio Belizandro Barbosa Rezende",
  "Faculdade de Tecnologia de Tatuí - Professor Wilson Roberto Ribeiro de Camargo",
  "Faculdade de Tecnologia de Pindamonhangaba",
  "Escola Técnica Estadual Carolina Carinhato Sampaio",
  "Escola Técnica Estadual Rodrigues de Abreu",
  "Escola Técnica Estadual Prof. Massuyuki Kawano",
  "Faculdade de Tecnologia da Zona Sul-São Paulo \"Dom Paulo Evaristo Arns\"",
  "Escola Técnica Estadual Professor Armando José Farinazzo",
  "Escola Técnica Estadual Tenente Aviador Gustavo Klug",
  "Escola Técnica Estadual Prof. Terezinha Monteiro dos Santos",
  "Escola Técnica Estadual Professora Maria Cristina Medeiros",
  "Escola Técnica Estadual Dr. Emilio Hernandez Aguilar",
  "Faculdade de Tecnologia de Carapicuíba",
  "Escola Técnica Estadual de Carapicuiba",
  "Escola Técnica Estadual Professor Fausto Mazzola",
  "Faculdade de Tecnologia de São José dos Campos - \"Professor Jessen Vidal\"",
  "Escola Técnica Estadual Prof. Carmine Biagio Tundisi",
  "Escola Técnica Estadual de Lins",
  "Escola Técnica Estadual Professor André Bogasian",
  "Escola Técnica Estadual Professor Rodolpho José Del Guerra",
  "Escola Técnica Estadual Professor Idio Zucchi",
  "Escola Técnica Estadual Alberto Santos Dumont",
  "Escola Técnica Estadual Praia Grande",
  "Escola Técnica Estadual Doutora Maria Augusta Saraiva",
  "Faculdade de Tecnologia de Itaquaquecetuba",
  "Escola Técnica Estadual Professora Nair Luccas Ribeiro",
  "Faculdade de Tecnologia de Presidente Prudente",
  "Escola Técnica Estadual Itanhaém",
  "Escola Técnica Estadual Parque da Juventude",
  "Faculdade de Tecnologia de Santo André",
  "Escola Técnica Estadual Vereador e Vice Prefeito Sérgio da Fonseca",
  "Escola Técnica Estadual Waldyr Duron Junior",
  "Faculdade de Tecnologia de Mogi Mirim \"Arthur de Azevedo\"",
  "Escola Técnica Estadual Prof. Mário Antônio Verza",
  "Escola Técnica Estadual de Araçatuba",
  "Escola Técnica Estadual Juscelino Kubitscheck de Oliveira",
  "Faculdade de Tecnologia de Guarulhos",
  "Faculdade de Tecnologia de São Caetano do Sul - Antonio Russo",
  "Escola Técnica Estadual de Itaquera",
  "Escola Técnica Estadual de Ferraz de Vanconcelos",
  "Faculdade de Tecnologia de Jales - \"Professor José Camargo\"",
  "Escola Técnica Estadual Sapopemba",
  "Faculdade de Tecnologia Nilo De Stéfani - Jaboticabal",
  "Faculdade de Tecnologia de Capão Bonito",
  "Faculdade de Tecnologia de Piracicaba - Dep Roque Trevisan",
  "Faculdade de Tecnologia de Sertãozinho Deputado Waldyr Alceu Trigo",
  "Faculdade de Tecnologia de Araçatuba - Prof Fernando Amaral de Almeida Prado",
  "Faculdade de Tecnologia de Itu",
  "Escola Técnica Estadual Vargem Grande do Sul",
  "Escola Técnica Estadual de Artes",
  "Escola Técnica Estadual de Cubatão",
  "Faculdade de Tecnologia de Catanduva",
  "Fatec Bragança - Jornalista Omair Fagundes de Oliveira",
  "Faculdade de Tecnologia de Mogi das Cruzes",
  "Escola Técnica Estadual Vila Formosa",
  "Escola Técnica Estadual Tereza Aparecida Cardoso Nunes de Oliveira",
  "Escola Técnica Estadual Profª Ermelinda Giannini Teixeira",
  "Escola Técnica Estadual de São Sebastião",
  "Faculdade de Tecnologia de São Sebastião",
  "Escola Técnica Estadual de Suzano",
  "Escola Técnica Estadual Gino Rezaghi",
  "Faculdade de Tecnologia de Lins \"Professor Antonio Seabra\"",
  "Escola Técnica Estadual Deputado Ary de Camargo Pedroso",
  "Escola Técnica Estadual Doutora Ruth Cardoso",
  "Escola Técnica Estadual Professora Ilza Nascimento Pintus",
  "Faculdade de Tecnologia de Bauru",
  "Escola Técnica Estadual Professor Elias Miguel Junior",
  "Escola Técnica Estadual de Monte Mor",
  "Escola Técnica Estadual de Cidade Tiradentes",
  "Escola Técnica Estadual Takashi Morita",
  "Escola Técnica Estadual de Campo Limpo Paulista",
  "Escola Técnica Estadual Prof. Jadyr Salles",
  "Escola Técnica Estadual de Piedade",
  "Faculdade de Tecnologia – FATEC do Ipiranga \"Pastor Enéas Tognini\"",
  "Escola Técnica Estadual de Heliópolis – Arquiteto Ruy Ohtake",
  "Escola Técnica Estadual Euro Albino de Souza",
  "Escola Técnica Estadual Professor Adhemar Batista Heméritas",
  "Escola Técnica Estadual de Tiquatira",
  "Faculdade de Tecnologia Padre Danilo José de Oliveira Ohl – Fatec Barueri",
  "Escola Técnica Estadual de Poá",
  "Escola Técnica Estadual Zona Leste",
  "Escola Técnica Estadual Professora Marinês Teodoro de Freitas Almeida",
  "Escola Técnica Estadual De Caraguatatuba",
  "Escola Técnica Estadual Ângelo Cavalheiro",
  "Escola Técnica Estadual Arnaldo Pereira Cheregatti",
  "Faculdade de Tecnologia de Osasco - Prefeito Hirant Sanazar",
  "Faculdade de Tecnologia de Diadema",
  "Escola Técnica Estadual João Maria Stevanatto",
  "Escola Técnica Estadual de Santa Isabel",
  "Escola Técnica Estadual Parque Belem",
  "Escola Técnica Estadual Jardim Angela",
  "Escola Técnica Estadual de Cotia",
  "Escola Técnica Estadual CEPAM",
  "Escola Técnica Estadual Abdias do Nascimento",
  "Escola Técnica Estadual Raposo Tavares",
  "Escola Técnica Estadual Gildo Marçal Bezerra Brandão",
  "Escola Técnica Estadual São Mateus",
  "Escola Técnica Estadual Jaraguá",
  "Escola Técnica Estadual Paulistano",
  "Escola Técnica Estadual Uirapuru",
  "Escola Técnica Estadual Francisco Morato",
  "Escola Técnica Estadual Prof. José Carlos Seno Júnior",
  "Escola Técnica Estadual Professor José Ignácio Azevedo Filho",
  "Escola Técnica Estadual Ferrucio Humberto Gazzetta",
  "Escola Técnica Estadual de Mairinque",
  "Escola Técnica Estadual Gustavo Teixeira",
  "Escola Técnica Estadual Santa Rosa do Viterbo",
  "Escola Técnica Estadual Irmã Agostina",
  "Escola Técnica Estadual de Registro",
  "Escola Técnica Estadual Padre Carlos Leôncio da Silva",
  "Escola Técnica Estadual de Embu",
  "Escola Técnica Estadual Dr. Celso Giglio",
  "Escola Técnica Estadual de Itararé",
  "Escola Técnica Estadual Cidade do Livro",
  "Escola Técnica Estadual de Barueri",
  "Escola Técnica Estadual Dr. Nelson Alves Vianna",
  "Escola Técnica Estadual de Mandaqui",
  "Escola Técnica Estadual de Cerquilho",
  "Escola Técnica Estadual de Itaquaquecetuba",
  "Faculdade de Tecnologia do Tatuapé - Victor Civita",
  "Faculdade de Tecnologia de Taubaté",
  "Escola Técnica Estadual Prof. Adolpho Arruda Mello",
  "Escola Técnica Estadual Jornalista Roberto Marinho",
  "Escola Técnica Estadual Profª Dra Doroti Q. Kanashiro",
  "Escola Técnica Estadual Alcides Cestari",
  "Escola Técnica Estadual Bento Carlos Botelho do Amaral",
  "Faculdade de Tecnologia de Itaquera - Professor Miguel Reale",
  "Faculdade de Tecnologia de Jacareí \"Professor Francisco de Moura\"",
  "Faculdade de Tecnologia de Pompéia - Shunji Nishimura",
  "Escola Técnica Estadual Santa Ifigênia",
  "Escola Técnica Estadual Darcy Pereira de Moraes",
  "Escola Técnica Estadual Bartolomeu Bueno da Silva - Anhanguera",
  "Escola Técnica Estadual de Ibaté",
  "Escola Técnica Estadual Armando Pannunzio",
  "Faculdade de Tecnologia de São Roque",
  "Escola Técnica Estadual de Peruíbe",
  "Escola Técnica Estadual de Esportes Curt Walter Otto Baumgart",
  "Escola Técnica Estadual Prefeito Braz Paschoalin",
  "Faculdade de Tecnologia de São Carlos",
  "Faculdade de Tecnologia de Cotia",
  "Escola Técnica Estadual de Mairiporã",
  "Faculdade de Tecnologia Sebrae",
  "Escola Técnica Estadual SEBRAE",
  "Escola Técnica Estadual Professora Luzia Maria Machado",
  "Faculdade de Tecnologia de Assis",
  "Faculdade de Tecnologia de Campinas",
  "Escola Técnica Estadual Santa Fé do Sul",
  "Faculdade de Tecnologia de Itapira - \"Ogari de Castro Pacheco\"",
  "Escola Técnica Estadual de Caieiras",
  "Faculdade de Tecnologia de Bebedouro \"Jorge Caram Sabbag\"",
  "Escola Técnica Estadual de Apiaí",
  "Escola Técnica Estadual de Rio Grande da Serra",
  "Faculdade de Tecnologia de Santana de Parnaíba",
  "Faculdade de Tecnologia de Ribeirão Preto",
  "Escola Técnica Estadual Itaquera II",
  "Faculdade de Tecnologia de Itatiba \"Maria Eunice Amadeo de Almeida\"",
  "Escola Técnica Estadual João Elias Margutti",
  "Faculdade de Tecnologia de Araraquara",
  "Escola Técnica Estadual de Porto Feliz",
  "Faculdade de Tecnologia de Araras",
  "Faculdade de Tecnologia de Adamantina",
  "Faculdade de Tecnologia de Ferraz de Vasconcelos",
  "Escola Técnica Estadual de Taboão da Serra",
  "Faculdade de Tecnologia de Franco da Rocha \"Giuliano Cecchettini\"",
  "Escola Técnica Estadual de Guarulhos",
  "Faculdade de Tecnologia de Sumaré",
  "Faculdade de Tecnologia de Matão",
  "Faculdade de Tecnologia de Barretos",
  "Faculdade de Tecnologia de Registro",
  "Escola Técnica Estadual de Itapevi",
  "Faculdade de Tecnologia de Votorantim",
  "Etec de Sumaré",
  "Etec de Cravinhos",
  "Etec de Guaíra",
  "Faculdade de Tecnologia de Esportes",
  "Etec de Bragança Paulista"
]

institutions = institution_names.map do |name|
  Institution.find_or_create_by!(name: name)
end
puts "Criadas #{institutions.count} instituições."

# 2. Create Courses with Faker (100 courses)
puts "Criando cursos falsos..."
courses = []
100.times do
  courses << Course.create!(
    name: Faker::Educator.course,
    course_type: [ "Técnico", "Superior" ].sample
  )
end
puts "Criados #{courses.count} cursos."

# 3. Create at least 2000 fake students and enrollments
puts "Criando 2000 alunos e suas matrículas..."
2000.times do |i|
  student = Student.create!(
    academic_id: Faker::Number.number(digits: 6).to_s,
    name: Faker::Name.name,
    email: Faker::Internet.email,
    date_of_birth: Faker::Date.birthday(min_age: 15, max_age: 22),
    contact_phone: Faker::PhoneNumber.cell_phone
  )

  # Each student receives between 1 and 3 enrollments
  rand(1..3).times do
    Enrollment.create!(
      student: student,
      institution: institutions.sample,
      course: courses.sample,
      shift: [ "Manhã", "Tarde", "Noite" ].sample,
      start_date: Faker::Date.between(from: 5.years.ago, to: 1.years.ago),
      end_date: Faker::Date.between(from: 364.days.ago, to: Date.today),
      status: [ "Ativa", "Concluída", "Pendente" ].sample
    )
  end

  # Log progress every 100 students
  puts "Criado aluno #{i + 1}" if (i + 1) % 100 == 0
end

puts "Seed concluído com sucesso!"
